"""add_user_cache_unlock_table

Revision ID: 466f73b9a093
Revises: e4bb19a5ac78
Create Date: 2026-08-02 22:45:36.830284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466f73b9a093'
down_revision: Union[str, Sequence[str], None] = 'e4bb19a5ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
