"""add_audit_fields_to_credit_ledger

Revision ID: 69bf9f4d7205
Revises: 956d1b4d88fa
Create Date: 2026-08-02 17:01:28.829884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bf9f4d7205'
down_revision: Union[str, Sequence[str], None] = '956d1b4d88fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CreditLedger', sa.Column('ownerId', sa.String(), server_default='', nullable=False))
    op.add_column('CreditLedger', sa.Column('triggeredByUserId', sa.String(), nullable=True))
    op.add_column('CreditLedger', sa.Column('queryTarget', sa.String(), nullable=True))
    op.add_column('CreditLedger', sa.Column('creditsSpent', sa.Integer(), nullable=True))
    op.add_column('CreditLedger', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index('CreditLedger_actionType_idx', 'CreditLedger', ['actionType'], unique=False)
    op.create_index('CreditLedger_ownerId_idx', 'CreditLedger', ['ownerId'], unique=False)
    op.create_index('CreditLedger_timestamp_idx', 'CreditLedger', ['timestamp'], unique=False)
    op.create_index(op.f('ix_CreditLedger_timestamp'), 'CreditLedger', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'CreditLedger', 'User', ['ownerId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'CreditLedger', 'User', ['triggeredByUserId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CreditLedger', type_='foreignkey')
    op.drop_constraint(None, 'CreditLedger', type_='foreignkey')
    op.drop_index(op.f('ix_CreditLedger_timestamp'), table_name='CreditLedger')
    op.drop_index('CreditLedger_timestamp_idx', table_name='CreditLedger')
    op.drop_index('CreditLedger_ownerId_idx', table_name='CreditLedger')
    op.drop_index('CreditLedger_actionType_idx', table_name='CreditLedger')
    op.drop_column('CreditLedger', 'timestamp')
    op.drop_column('CreditLedger', 'creditsSpent')
    op.drop_column('CreditLedger', 'queryTarget')
    op.drop_column('CreditLedger', 'triggeredByUserId')
    op.drop_column('CreditLedger', 'ownerId')
    # ### end Alembic commands ###
