"""add_track_aio_to_tracked_keyword

Revision ID: 956d1b4d88fa
Revises: c4d5e6f7a8b9
Create Date: 2026-08-01 23:43:18.235495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '956d1b4d88fa'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('KeywordCluster_projectId_idx'), table_name='KeywordCluster')
    op.drop_table('KeywordCluster')
    op.add_column('CreditLedger', sa.Column('amountPaidInr', sa.Float(), nullable=True))
    op.add_column('CreditLedger', sa.Column('status', sa.String(), server_default='completed', nullable=False))
    op.add_column('CreditLedger', sa.Column('invoiceNumber', sa.String(), nullable=True))
    op.add_column('TrackedKeyword', sa.Column('trackAio', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackedKeyword', 'trackAio')
    op.drop_column('CreditLedger', 'invoiceNumber')
    op.drop_column('CreditLedger', 'status')
    op.drop_column('CreditLedger', 'amountPaidInr')
    op.create_table('KeywordCluster',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('KeywordCluster_projectId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('KeywordCluster_pkey'))
    )
    op.create_index(op.f('KeywordCluster_projectId_idx'), 'KeywordCluster', ['projectId'], unique=False)
    # ### end Alembic commands ###
