"""Add TeamInvite and startDate to ScheduledReport

Revision ID: c27c7b237d78
Revises: 
Create Date: 2026-07-28 11:38:54.441188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c27c7b237d78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('CompetitorRank_competitorId_idx'), table_name='CompetitorRank')
    op.drop_index(op.f('CompetitorRank_projectId_idx'), table_name='CompetitorRank')
    op.drop_table('CompetitorRank')
    op.drop_index(op.f('Notification_projectId_idx'), table_name='notifications')
    op.drop_index(op.f('Notification_status_idx'), table_name='notifications')
    op.drop_index(op.f('Notification_userId_idx'), table_name='notifications')
    op.drop_table('notifications')
    op.alter_column('Audit', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Audit', 'projectId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Audit', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('Audit_projectId_fkey'), 'Audit', type_='foreignkey')
    op.create_foreign_key(None, 'Audit', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.alter_column('AuditIssue', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'auditId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('AuditIssue_auditId_fkey'), 'AuditIssue', type_='foreignkey')
    op.create_foreign_key(None, 'AuditIssue', 'Audit', ['auditId'], ['id'], ondelete='CASCADE')
    op.alter_column('Competitor', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Competitor', 'projectId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Competitor', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Competitor', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('Competitor_projectId_fkey'), 'Competitor', type_='foreignkey')
    op.create_foreign_key(None, 'Competitor', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.alter_column('Keyword', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Keyword', 'projectId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Keyword', 'keyword',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Keyword', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Keyword', 'device',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('Keyword_projectId_idx', 'Keyword', ['projectId'], unique=False)
    op.drop_constraint(op.f('Keyword_projectId_fkey'), 'Keyword', type_='foreignkey')
    op.create_foreign_key(None, 'Keyword', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Notification_projectId_fkey1'), 'Notification', type_='foreignkey')
    op.create_foreign_key(None, 'Notification', 'Project', ['projectId'], ['id'], ondelete='SET NULL')
    op.alter_column('Project', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Project', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Project', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Project', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('Project_userId_fkey'), 'Project', type_='foreignkey')
    op.create_foreign_key(None, 'Project', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('RankResult', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('RankResult', 'projectId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('RankResult', 'keywordText',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('RankResult', 'device',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('RankResult', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('RankResult', 'keywordId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('RankResult_keywordId_fkey'), 'RankResult', type_='foreignkey')
    op.drop_constraint(op.f('RankResult_projectId_fkey'), 'RankResult', type_='foreignkey')
    op.create_foreign_key(None, 'RankResult', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'RankResult', 'Keyword', ['keywordId'], ['id'], ondelete='CASCADE')
    op.alter_column('Report', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Report', 'projectId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Report', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Report', 'period',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Report', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'COMPLETED'::text"))
    op.drop_constraint(op.f('Report_projectId_fkey'), 'Report', type_='foreignkey')
    op.create_foreign_key(None, 'Report', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.add_column('ScheduledReport', sa.Column('startDate', sa.DateTime(), nullable=True))
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'passwordHash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.alter_column('User', 'passwordHash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('ScheduledReport', 'startDate')
    op.drop_constraint(None, 'Report', type_='foreignkey')
    op.create_foreign_key(op.f('Report_projectId_fkey'), 'Report', 'Project', ['projectId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('Report', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'COMPLETED'::text"))
    op.alter_column('Report', 'period',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Report', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Report', 'projectId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Report', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'RankResult', type_='foreignkey')
    op.drop_constraint(None, 'RankResult', type_='foreignkey')
    op.create_foreign_key(op.f('RankResult_projectId_fkey'), 'RankResult', 'Project', ['projectId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('RankResult_keywordId_fkey'), 'RankResult', 'Keyword', ['keywordId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('RankResult', 'keywordId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('RankResult', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('RankResult', 'device',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('RankResult', 'keywordText',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('RankResult', 'projectId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('RankResult', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Project', type_='foreignkey')
    op.create_foreign_key(op.f('Project_userId_fkey'), 'Project', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('Project', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Project', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Project', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Project', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.create_foreign_key(op.f('Notification_projectId_fkey1'), 'Notification', 'Project', ['projectId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Keyword', type_='foreignkey')
    op.create_foreign_key(op.f('Keyword_projectId_fkey'), 'Keyword', 'Project', ['projectId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('Keyword_projectId_idx', table_name='Keyword')
    op.alter_column('Keyword', 'device',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Keyword', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Keyword', 'keyword',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Keyword', 'projectId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Keyword', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Competitor', type_='foreignkey')
    op.create_foreign_key(op.f('Competitor_projectId_fkey'), 'Competitor', 'Project', ['projectId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('Competitor', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Competitor', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Competitor', 'projectId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Competitor', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'AuditIssue', type_='foreignkey')
    op.create_foreign_key(op.f('AuditIssue_auditId_fkey'), 'AuditIssue', 'Audit', ['auditId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('AuditIssue', 'severity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'auditId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('AuditIssue', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Audit', type_='foreignkey')
    op.create_foreign_key(op.f('Audit_projectId_fkey'), 'Audit', 'Project', ['projectId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('Audit', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Audit', 'projectId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Audit', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'UNREAD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entityId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('readAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('Notification_projectId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Notification_userId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Notification_pkey'))
    )
    op.create_index(op.f('Notification_userId_idx'), 'notifications', ['userId'], unique=False)
    op.create_index(op.f('Notification_status_idx'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('Notification_projectId_idx'), 'notifications', ['projectId'], unique=False)
    op.create_table('CompetitorRank',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('competitorId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keywordText', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checkedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competitorId'], ['Competitor.id'], name=op.f('CompetitorRank_competitorId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('CompetitorRank_projectId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('CompetitorRank_pkey'))
    )
    op.create_index(op.f('CompetitorRank_projectId_idx'), 'CompetitorRank', ['projectId'], unique=False)
    op.create_index(op.f('CompetitorRank_competitorId_idx'), 'CompetitorRank', ['competitorId'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    # ### end Alembic commands ###
