"""add purchase_type to payment_order

Revision ID: e4bb19a5ac78
Revises: d4e5f6a7b8c9
Create Date: 2026-08-02 20:56:34.540416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bb19a5ac78'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentOrder', sa.Column('purchaseType', sa.String(), server_default='SUBSCRIPTION_UPGRADE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PaymentOrder', 'purchaseType')
    # ### end Alembic commands ###
