import { ArrowRight, BarChart3, Bot, FileText, Gauge, Search, Sparkles, Target } from 'lucide-react';
import { Link } from '../lib/navigation';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { faqItems } from '../content/public';

const capabilities = [
  [Target, 'Rank tracking', 'Track current Google positions, ranking URLs, visibility, and Top 100 SERP results for the keywords you choose.'],
  [Gauge, 'Keyword intelligence', 'Review search volume, keyword difficulty, CPC, competition, and intent alongside current rankings.'],
  [Bot, 'AI Overview visibility', 'See current AI Overview presence and available description data without claiming historical AIO snapshots.'],
  [Search, 'Research & competitor discovery', 'Use Keyword Research and Competitor Spy within the allowance of your paid plan.'],
  [Sparkles, 'Controlled refreshes', 'Manage active and inactive keywords, use Manual Refresh when included, and keep scheduled tracking focused.'],
  [FileText, 'Reports', 'Prepare a keyword report from the data already available for your selected project.'],
];

export default function HomePage() {
  return <>
    <section className="overflow-hidden border-b border-border bg-gradient-to-b from-brand-50 via-surface to-surface-subtle">
      <div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr,.95fr] lg:px-8 lg:py-24">
        <div className="self-center"><p className="inline-flex rounded-full bg-brand-100 px-3 py-1 text-sm font-semibold text-brand-800">SEO visibility, without the clutter</p><h1 className="mt-5 max-w-3xl text-4xl font-bold tracking-tight text-text-primary sm:text-5xl lg:text-6xl">Track rankings. Understand search visibility. Make better SEO decisions.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-text-secondary">RankCare keeps keyword tracking, project management, search metrics, research, and reports in one practical workspace.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register"><Button size="lg">Start free <ArrowRight className="h-4 w-4" aria-hidden="true" /></Button></Link><Link to="/features"><Button size="lg" variant="outline">Explore features</Button></Link></div><p className="mt-4 text-sm text-text-muted">The Free plan is permanent. Paid features and scheduled tracking depend on your plan.</p></div>
        <ProductPreview />
      </div>
    </section>
    <Section eyebrow="Product capabilities" title="A clear view of the work that moves SEO forward" intro="Every capability below reflects the RankCare product as it exists today."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([Icon, title, description]) => <Card key={title} padding="p-6"><Icon className="h-5 w-5 text-brand-700" aria-hidden="true" /><h3 className="mt-4 text-lg font-semibold text-text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{description}</p></Card>)}</div></Section>
    <Section eyebrow="How RankCare fits your workflow" title="From a project to useful search insight"><ol className="grid gap-4 md:grid-cols-5">{['Create a project', 'Add keywords', 'Track rankings', 'Review metrics', 'Research opportunities'].map((step, index) => <li key={step} className="relative rounded-xl border border-border bg-surface p-5"><span className="text-sm font-semibold text-brand-700">0{index + 1}</span><p className="mt-3 font-semibold text-text-primary">{step}</p>{index < 4 ? <ArrowRight className="absolute -right-7 top-1/2 hidden h-5 w-5 -translate-y-1/2 text-brand-300 md:block" aria-hidden="true" /> : null}</li>)}</ol></Section>
    <section className="border-y border-border bg-surface"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-700">AI Overview tracking</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-text-primary">Keep current AIO visibility in context.</h2><p className="mt-4 leading-7 text-text-secondary">RankCare can surface whether a tracked keyword currently shows an AI Overview, plus the available current description data. It does not present this as dedicated historical AIO reporting.</p></div><Card padding="p-6" className="bg-surface-subtle"><p className="text-sm font-semibold text-text-primary">Current keyword state</p><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between rounded-lg bg-surface p-3"><span className="text-text-secondary">AI Overview</span><span className="font-semibold text-active">Present</span></div><div className="flex justify-between rounded-lg bg-surface p-3"><span className="text-text-secondary">Ranking URL</span><span className="font-semibold text-text-primary">Available</span></div><p className="pt-1 text-xs leading-5 text-text-muted">Illustrative product state — not customer performance data.</p></div></Card></div></section>
    <Section eyebrow="Plans that stay transparent" title="Start small, then add room for your workflow" intro="Compare Free, Starter, Pro, Agency, and a sales-assisted Custom option. Limits, credits, and paid-feature allowances are shown directly on the pricing page."><Link to="/pricing"><Button>View pricing <ArrowRight className="h-4 w-4" aria-hidden="true" /></Button></Link></Section>
    <Section eyebrow="FAQ" title="Questions people ask before tracking"><div className="grid gap-4 md:grid-cols-2">{faqItems.slice(0, 4).map(([question, answer]) => <Card key={question} padding="p-5"><h3 className="font-semibold text-text-primary">{question}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{answer}</p></Card>)}</div><Link className="mt-6 inline-flex text-sm font-semibold text-brand-700 hover:text-brand-800" to="/faq">Read all FAQs <ArrowRight className="ml-1 h-4 w-4" aria-hidden="true" /></Link></Section>
    <section className="bg-brand-800"><div className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-6 lg:px-8"><h2 className="text-3xl font-bold tracking-tight text-white">Give your SEO work a clearer home.</h2><p className="mt-4 text-brand-100">Create a Free account to organize a project and start tracking the keywords that matter.</p><Link className="mt-7 inline-block" to="/register"><Button size="lg" variant="secondary">Create a Free account</Button></Link></div></section>
  </>;
}

function Section({ eyebrow, title, intro, children }) { return <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-text-primary">{title}</h2>{intro ? <p className="mt-4 leading-7 text-text-secondary">{intro}</p> : null}</div><div className="mt-8">{children}</div></section>; }

function ProductPreview() { return <Card padding="p-0" className="overflow-hidden border-brand-100 shadow-elevated"><div className="flex items-center gap-2 border-b border-border bg-surface-subtle px-5 py-3"><span className="h-2.5 w-2.5 rounded-full bg-danger" /><span className="h-2.5 w-2.5 rounded-full bg-warning" /><span className="h-2.5 w-2.5 rounded-full bg-success" /><span className="ml-2 text-xs font-medium text-text-muted">RankCare workspace</span></div><div className="space-y-4 p-5 sm:p-7"><div className="grid grid-cols-2 gap-3"><PreviewMetric label="Tracked keywords" value="Current view" /><PreviewMetric label="AIO coverage" value="Current state" /></div><div className="rounded-xl border border-border bg-surface-subtle p-4"><p className="text-sm font-semibold text-text-primary">Keyword table</p><div className="mt-3 space-y-2">{['Search visibility', 'Ranking URL', 'Volume, KD & CPC'].map((item, index) => <div key={item} className="flex items-center justify-between rounded-lg bg-surface px-3 py-2 text-sm"><span className="text-text-secondary">{item}</span><span className="font-medium text-text-primary">{index === 1 ? 'Available' : 'Tracked'}</span></div>)}</div></div><p className="text-xs leading-5 text-text-muted">Illustrative interface. No customer metrics or performance claims are shown.</p></div></Card>; }
function PreviewMetric({ label, value }) { return <div className="rounded-xl bg-brand-50 p-4"><p className="text-xs font-medium text-text-secondary">{label}</p><p className="mt-2 text-lg font-bold text-brand-800">{value}</p></div>; }
