'use client';

import { useState } from 'react';
import { BarChart3, Bot, ChevronDown, FileText, Search, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { Link } from '../lib/navigation';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { brand, contactHref } from '../config/brand';
import { faqItems, legalContent } from '../content/public';

const features = [
  ['Rank tracking', Target, 'Current positions, ranking URLs, visibility, Top 100 SERP information, and project-scoped keyword management.'],
  ['Keyword metrics', BarChart3, 'Search volume, keyword difficulty, CPC, competition, intent, and related metrics where available.'],
  ['AI Overview tracking', Bot, 'Current AI Overview presence and description data where DataForSEO returns it; this is not presented as historical AIO reporting.'],
  ['Keyword Research', Search, 'Plan-limited keyword research for discovering ideas and reviewing available keyword data.'],
  ['Competitor Spy', Sparkles, 'Plan-limited competitor keyword discovery for reviewing competing domains.'],
  ['Refresh & reporting', FileText, 'Manual Refresh on paid plans, scheduled tracking for eligible plans, and keyword report generation.'],
];

export function FeaturesPage() { return <PublicPage eyebrow="Features" title="Real SEO workflow tools, presented clearly." intro="RankCare combines the product capabilities that are available today. Feature availability depends on your selected plan."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([title, Icon, text]) => <Card key={title} padding="p-6"><Icon className="h-5 w-5 text-brand-700" aria-hidden="true" /><h2 className="mt-4 text-lg font-semibold text-text-primary">{title}</h2><p className="mt-2 text-sm leading-6 text-text-secondary">{text}</p></Card>)}</div><Card padding="p-6" className="mt-8 bg-surface-subtle"><h2 className="text-lg font-semibold text-text-primary">Plan-aware controls</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-text-secondary">Free accounts can organize one project and track up to five keywords. Paid feature allowances, credits, and automatic tracking are enforced by the product rather than implied by the marketing site.</p><Link className="mt-4 inline-block" to="/pricing"><Button variant="outline">Compare plans</Button></Link></Card></PublicPage>; }

export function AboutPage() { return <PublicPage eyebrow="About RankCare" title="Useful SEO data should be easier to work with." intro="RankCare is a focused workspace for teams that want to organize rank tracking, search visibility, and keyword research without treating every SEO decision as a dashboard spectacle."><div className="grid gap-5 md:grid-cols-3"><Statement title="Clear tracking" text="Keep projects, keywords, current positions, and ranking URLs in a structured workflow." /><Statement title="Practical context" text="Review keyword metrics, current AIO visibility, research results, and reports where they inform the next decision." /><Statement title="Transparent controls" text="Plans, feature allowances, credits, and keyword lifecycle states are surfaced in the product." /></div></PublicPage>; }

export function ContactPage() { const support = brand.supportEmail; const sales = brand.salesEmail; return <PublicPage eyebrow="Contact" title="Talk to the right RankCare team." intro="Use the configured contact channel for product support or a tailored plan discussion."><div className="grid gap-5 md:grid-cols-2"><ContactCard title="Product support" email={support} body="For account, billing, and product assistance." /><ContactCard title="Sales & Custom plans" email={sales} body="For higher limits or a tailored RankCare setup." /></div><Card padding="p-6" className="mt-6"><h2 className="font-semibold text-text-primary">Before production launch</h2><p className="mt-2 text-sm leading-6 text-text-secondary">RankCare needs finalized support and sales email addresses, legal company name, business address where required, and approved social links. These are intentionally environment-configured rather than invented in the public site.</p></Card></PublicPage>; }

export function FaqPage() { const [open, setOpen] = useState(null); return <PublicPage eyebrow="FAQ" title="Straight answers about RankCare."><div className="divide-y divide-border rounded-xl border border-border bg-surface">{faqItems.map(([question, answer], index) => <div key={question}><button type="button" className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left font-semibold text-text-primary focus:outline-none focus:ring-4 focus:ring-inset focus:ring-brand-100" aria-expanded={open === index} onClick={() => setOpen(open === index ? null : index)}><span>{question}</span><ChevronDown aria-hidden="true" className={`h-5 w-5 shrink-0 text-brand-700 transition-transform ${open === index ? 'rotate-180' : ''}`} /></button>{open === index ? <p className="px-5 pb-5 text-sm leading-6 text-text-secondary">{answer}</p> : null}</div>)}</div></PublicPage>; }

export function LegalPage({ kind }) { const content = legalContent[kind]; return <PublicPage eyebrow="Legal" title={content.title} intro={content.intro}><div className="max-w-3xl space-y-6">{content.sections.map(([heading, body]) => <Card key={heading} padding="p-6"><h2 className="text-lg font-semibold text-text-primary">{heading}</h2><p className="mt-3 text-sm leading-7 text-text-secondary">{body}</p></Card>)}</div></PublicPage>; }

export function PublicPage({ eyebrow, title, intro, children }) { return <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-700">{eyebrow}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-text-primary sm:text-5xl">{title}</h1>{intro ? <p className="mt-5 text-lg leading-8 text-text-secondary">{intro}</p> : null}</div><div className="mt-10">{children}</div></section>; }
function Statement({ title, text }) { return <Card padding="p-6"><ShieldCheck className="h-5 w-5 text-brand-700" aria-hidden="true" /><h2 className="mt-4 font-semibold text-text-primary">{title}</h2><p className="mt-2 text-sm leading-6 text-text-secondary">{text}</p></Card>; }
function ContactCard({ title, email, body }) { return <Card padding="p-6"><h2 className="text-lg font-semibold text-text-primary">{title}</h2><p className="mt-2 text-sm leading-6 text-text-secondary">{body}</p>{email ? <a className="mt-5 inline-flex rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-700 focus:outline-none focus:ring-4 focus:ring-brand-200" href={contactHref(email, `${title} enquiry`)}>{email}</a> : <p className="mt-5 rounded-lg bg-surface-subtle px-3 py-2 text-sm text-text-muted">Contact address to be confirmed before launch.</p>}</Card>; }
