'use client';

import { useEffect, useState } from 'react';
import Alert from '../../../../src/components/ui/Alert';
import Button from '../../../../src/components/ui/Button';
import Card from '../../../../src/components/ui/Card';
import { apiRequest } from '../../../../src/lib/api';

const planFields = ['monthlyPriceInr', 'monthlyPriceUsd', 'projectLimit', 'keywordLimit', 'monthlyCredits', 'automaticCredits', 'manualRefreshLimit', 'keywordResearchLimit', 'competitorSpyLimit'];

export default function CommercialAdminPage() {
  const [plans, setPlans] = useState([]); const [packages, setPackages] = useState([]); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const [p, t] = await Promise.all([apiRequest('/admin/commercial/plans'), apiRequest('/admin/commercial/top-up-packages')]); setPlans(p.data || []); setPackages(t.data || []); } catch (e) { setError(e.message || 'Unable to load commercial configuration.'); } };
  useEffect(() => { load(); }, []);
  const savePlan = async (plan) => { try { await apiRequest(`/admin/commercial/plans/${plan.key}`, { method: 'PUT', body: JSON.stringify(plan) }); setMessage(`${plan.name} saved.`); load(); } catch (e) { setError(e.message || 'Unable to save plan.'); } };
  const savePackage = async (pack) => { try { await apiRequest(`/admin/commercial/top-up-packages/${pack.id}`, { method: 'PUT', body: JSON.stringify(pack) }); setMessage(`${pack.name} saved.`); load(); } catch (e) { setError(e.message || 'Unable to save package.'); } };
  const changePlan = (key, field, value) => setPlans((all) => all.map((p) => p.key === key ? { ...p, [field]: Number(value) } : p));
  const changePackage = (id, field, value) => setPackages((all) => all.map((p) => p.id === id ? { ...p, [field]: field === 'name' ? value : field === 'isActive' ? value : Number(value) } : p));
  return <main className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6"><div><h1 className="text-3xl font-bold text-text-primary">Commercial configuration</h1><p className="mt-2 text-text-secondary">Server-authoritative prices, allocations, and credit packages. Annual prices are calculated as monthly × 11.</p><p className="mt-2 text-sm text-text-muted">Changes apply to new purchases and future billing cycles; active-cycle entitlements remain unchanged.</p></div>{error ? <Alert variant="error" message={error} onDismiss={() => setError('')} /> : null}{message ? <Alert variant="success" message={message} onDismiss={() => setMessage('')} /> : null}<section className="grid gap-5 lg:grid-cols-2">{plans.map((plan) => <Card key={plan.key} padding="p-5"><div className="flex items-baseline justify-between"><h2 className="text-xl font-semibold text-text-primary">{plan.name}</h2><span className="text-sm text-text-muted">Annual: ₹{plan.yearlyPriceInr} / ${plan.yearlyPriceUsd}</span></div><div className="mt-4 grid grid-cols-2 gap-3">{planFields.map((field) => <label key={field} className="text-sm font-medium text-text-secondary">{field}<input className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-text-primary" type="number" min="0" value={plan[field]} onChange={(e) => changePlan(plan.key, field, e.target.value)} /></label>)}</div><p className="mt-3 text-sm text-text-muted">Spendable credits: {plan.monthlyCredits - plan.automaticCredits}</p><Button className="mt-4" onClick={() => savePlan(plan)}>Save {plan.name}</Button></Card>)}</section><section><h2 className="text-2xl font-bold text-text-primary">Top-up packages</h2><div className="mt-4 space-y-3">{packages.map((pack) => <Card key={pack.id} padding="p-4" className="grid gap-3 md:grid-cols-6"><input aria-label={`${pack.name} name`} className="rounded-lg border border-border px-3 py-2" value={pack.name} onChange={(e) => changePackage(pack.id, 'name', e.target.value)} />{['credits', 'priceInr', 'priceUsd', 'displayOrder'].map((field) => <input key={field} aria-label={`${pack.name} ${field}`} className="rounded-lg border border-border px-3 py-2" type="number" min="0" value={pack[field]} onChange={(e) => changePackage(pack.id, field, e.target.value)} />)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pack.isActive} onChange={(e) => changePackage(pack.id, 'isActive', e.target.checked)} /> Active</label><Button variant="outline" onClick={() => savePackage(pack)}>Save</Button></Card>)}</div></section></main>;
}
