'use client'
export const TRIAL_DAYS = 7;

export const PLANS = [
  {
    key: "free_trial",
    name: "Free Trial",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "7-day free trial to test RankCare.",
    highlighted: false,
    cta: "Start Free Trial",
    refreshFrequency: "weekly",
    monthlyCredits: 150,
    bulkMaxKeywords: 10,
    competitorSpyLimit: 20,
    weeklyTrackingEnabled: false,
    maxWeeklyTrackedKeywords: 0,
    features: [
      "150 total credits",
      "10 keywords max per bulk list",
      "20 competitor spy rows",
      "Weekly tracking disabled",
      "7-day trial period",
    ],
  },
    {
    key: "starter",
    name: "Starter",
    monthlyPrice: 639,
    yearlyPrice: 6932,
    description: "Best for freelancers and small websites starting SEO tracking.",
    highlighted: false,
    cta: "Upgrade to Starter",
    refreshFrequency: "weekly",
    monthlyCredits: 4000,
    bulkMaxKeywords: 100,
    competitorSpyLimit: 100,
    weeklyTrackingEnabled: true,
    maxWeeklyTrackedKeywords: 1000,
    aioKeywordsMonitored: 100,
    features: [
      "4,000 credits / month",
      "100 keywords max per bulk list",
      "100 competitor spy rows",
      "1,000 weekly tracked keywords",
      "100 AIO tracked keywords",
      "1 project",
    ],
  },
  {
    key: "pro",
    name: "Pro",
    monthlyPrice: 1589,
    yearlyPrice: 17235,
    description: "Ideal for growing businesses that need stronger reporting and tracking.",
    highlighted: true,
    cta: "Upgrade to Pro",
    refreshFrequency: "weekly",
    monthlyCredits: 10000,
    bulkMaxKeywords: 500,
    competitorSpyLimit: 300,
    weeklyTrackingEnabled: true,
    maxWeeklyTrackedKeywords: 4000,
    features: [
      "10,000 credits / month",
      "500 keywords max per bulk list",
      "300 competitor spy rows",
      "4,000 weekly tracked keywords",
      "5 projects",
      "100 AIO keywords",
    ],
  },
  {
    key: "agency",
    name: "Agency",
    monthlyPrice: 3969,
    yearlyPrice: 43058,
    description: "Built for agencies handling multiple clients and organized client delivery.",
    highlighted: false,
    cta: "Upgrade to Agency",
    refreshFrequency: "weekly",
    monthlyCredits: 25000,
    bulkMaxKeywords: 1000,
    competitorSpyLimit: 1000,
    weeklyTrackingEnabled: true,
    maxWeeklyTrackedKeywords: 10000,
    features: [
      "25,000 credits / month",
      "1,000 keywords max per bulk list",
      "1,000 competitor spy rows",
      "10,000 weekly tracked keywords",
      "20 projects",
      "500 AIO keywords",
    ],
  },
  {
    key: "enterprise",
    name: "Enterprise",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Custom bulk allocation for large teams. Contact sales for pricing.",
    highlighted: false,
    cta: "Contact Sales",
    refreshFrequency: "weekly",
    monthlyCredits: 999999,
    bulkMaxKeywords: 5000,
    competitorSpyLimit: 5000,
    weeklyTrackingEnabled: true,
    maxWeeklyTrackedKeywords: 99999,
    features: [
      "Tailored bulk allocation",
      "5,000 keywords max per bulk list",
      "5,000 competitor spy rows",
      "Unlimited weekly tracked keywords",
      "Unlimited projects",
      "Dedicated support",
    ],
  },
];

export const CREDIT_PACKS = [
  { credits: 1000, priceInr: 150, popular: false },
  { credits: 2000, priceInr: 300, popular: false },
  { credits: 3000, priceInr: 450, popular: true },
  { credits: 4000, priceInr: 600, popular: false },
];

export const PLAN_COMPARISON = [
  { label: "Monthly Credits", free_trial: "150", starter: "4,000", pro: "10,000", agency: "25,000", enterprise: "Custom" },
  { label: "Bulk Max Keywords", free_trial: "10", starter: "100", pro: "500", agency: "1,000", enterprise: "5,000" },
  { label: "Competitor Spy Rows", free_trial: "20", starter: "100", pro: "300", agency: "1,000", enterprise: "5,000" },
  { label: "Weekly Tracking", free_trial: "Disabled", starter: "1,000", pro: "4,000", agency: "10,000", enterprise: "Unlimited" },
  { label: "AIO Tracked Keywords", free_trial: "0", starter: "100", pro: "100", agency: "500", enterprise: "Unlimited" },
];

export const VALID_PLAN_KEYS = PLANS.map((plan) => plan.key);

export const CREDIT_ITEMS = [
  { icon: "⚡", label: "Database Cache Hit", credits: 0, description: "Recent keyword data served instantly" },
  { icon: "🔍", label: "Single Keyword Search", credits: 15, description: "Live keyword metrics lookup" },
  { icon: "📦", label: "Bulk Keywords (up to 100)", credits: 50, description: "Process multiple keywords at once" },
  { icon: "🕵️‍♂️", label: "Competitor Spy Report", credits: 30, description: "Full competitor keyword analysis" },
  { icon: "📈", label: "Track 1 Keyword Weekly", credits: 20, description: "Upfront deduction for monthly position monitoring" },
];
