'use client'
export const TRIAL_DAYS = 7;

export const PLANS = [
  {
    key: "free_trial",
    name: "Free Trial",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "7-day free trial to test RankCare.",
    highlighted: false,
    cta: "Start Free Trial",
    refreshFrequency: "weekly",
    limits: {
      projects: 1,
      keywords: 5,
      competitorsPerProject: 3,
      reportsPerMonth: 1,
      teamMembers: 1,
      aioKeywordsMonitored: 0,
      keywordResearchCreditsPerMonth: 10,
    },
    features: [
      "1 project",
      "Track up to 5 keywords",
      "Weekly rank updates",
      "1 report / month",
      "Limited keyword research",
      "No AIO tracking",
    ],
  },
  {
    key: "starter",
    name: "Starter",
    monthlyPrice: 999,
    yearlyPrice: 9599,
    description: "Best for freelancers and small websites starting SEO tracking.",
    highlighted: false,
    cta: "Start Starter",
    refreshFrequency: "weekly",
    limits: {
      projects: 1,
      keywords: 100,
      competitorsPerProject: 3,
      reportsPerMonth: 1,
      teamMembers: 1,
      aioKeywordsMonitored: 0,
      keywordResearchCreditsPerMonth: 50,
    },
    features: [
      "1 project",
      "Track up to 100 keywords",
      "Weekly rank updates",
      "1 report / month",
      "50 keyword research credits / month",
      "No AIO tracking",
      "Email support",
    ],
  },
  {
    key: "pro",
    name: "Pro",
    monthlyPrice: 2499,
    yearlyPrice: 23999,
    description: "Ideal for growing businesses that need stronger reporting and tracking.",
    highlighted: true,
    cta: "Start Pro",
    refreshFrequency: "weekly",
    limits: {
      projects: 3,
      keywords: 200,
      competitorsPerProject: 6,
      reportsPerMonth: 6,
      teamMembers: 3,
      aioKeywordsMonitored: 50,
      keywordResearchCreditsPerMonth: 200,
    },
    features: [
      "Up to 3 projects",
      "Track up to 200 keywords",
      "Weekly rank updates",
      "6 reports / month",
      "200 keyword research credits / month",
      "50 AIO tracked keywords",
      "Competitor tracking",
      "Priority support",
    ],
  },
  {
    key: "agency",
    name: "Agency",
    monthlyPrice: 4999,
    yearlyPrice: 47999,
    description: "Built for agencies handling multiple clients and organized client delivery.",
    highlighted: false,
    cta: "Start Agency",
    refreshFrequency: "weekly",
    limits: {
      projects: 10,
      keywords: 500,
      competitorsPerProject: 10,
      reportsPerMonth: 25,
      teamMembers: 5,
      aioKeywordsMonitored: 200,
      keywordResearchCreditsPerMonth: 500,
    },
    features: [
      "Up to 10 projects",
      "Track up to 500 keywords",
      "Weekly rank updates",
      "25 reports / month",
      "500 keyword research credits / month",
      "200 AIO tracked keywords",
      "Team access",
      "Premium support",
    ],
  },
];

export const PLAN_COMPARISON = [
  { label: "Projects", freeTrial: "1", starter: "1", pro: "3", agency: "10" },
  { label: "Tracked keywords", freeTrial: "5", starter: "100", pro: "200", agency: "500" },
  { label: "Competitors / project", freeTrial: "3", starter: "3", pro: "6", agency: "10" },
  { label: "Reports / month", freeTrial: "1", starter: "1", pro: "6", agency: "25" },
  { label: "Team members", freeTrial: "1", starter: "1", pro: "3", agency: "5" },
  { label: "Refresh frequency", freeTrial: "Weekly", starter: "Weekly", pro: "Weekly", agency: "Weekly" },
  { label: "AIO tracked keywords", freeTrial: "0", starter: "0", pro: "50", agency: "200" },
  { label: "Keyword research credits / month", freeTrial: "10", starter: "50", pro: "200", agency: "500" },
];

export const VALID_PLAN_KEYS = PLANS.map((plan) => plan.key);
